### ISSUE TITLE
Shift X no longer working

### ISSUE THREAD

**Issue by Avitale34** [zeel01/TokenHUDArtButton#4]
I am having an issue getting shift X to work properly, did something change?

**Comment by zeel01** [comment]
Nothing has changed, and it's working fine for me. It's possible that there is an interaction with another module. Do you get any error messages in the console that may pertain to this issue?

**Comment by Fraxinus1753** [comment]
I ran some tests and it appears there is an incompatibility with the Show Drag Distance module. I think it comes from one of the latest updates of this module as it worked before. 

However, I don't think Show Drag Distance does anything with shift + X per se (nothing happens when I use it at least), so I really don't know where the incompatibility comes from. Holding shift in Show Drag Distance allows you to place your token off grid, but if that the source of the problem, then for some strange reason it doesn't interfere with the shift + Z command of Show Art. 

Let me know if I can give you more info!

**Comment by zeel01** [comment]
This appears to be an issue only Show Drag Distance can solve, it uses a press of the X key to remove a waypoint, or cancel the ruler or something, I'm not completely certain how it's supposed to work. But the end result is that it eats the key event, even when it isn't actively doing anything.

**Comment by Fraxinus1753** [comment]
Alright thanks for checking, I'll leave a comment under Show Drag Distance then.

**Comment by DeadlyArtist** [comment]
For me it doesn't work as well. But I have Show Drag Distance module disabled

**Comment by zeel01** [comment]
@DeadlyArtist Does it work when this is the only module you have enabled?

**Comment by DeadlyArtist** [comment]
nope, it does not work even on empty world. (foundry version 0.6.6 and dnd5e)
